const dataDemo = {
    code: "00",
    message: "Success",
    data: [{
            queryid: 4811,
            checkindate: "10/03/2019",
            checkoutdate: "12/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "01",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9B",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:40",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:40",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4777,
                queryid: 4811,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "10/03/2019",
            checkoutdate: "12/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Xịn",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "10",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "20/03/2019",
            checkoutdate: "21/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "03",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "20/03/2019",
            checkoutdate: "21/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "06",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "20/03/2019",
            checkoutdate: "21/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "08",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "20/03/2019",
            checkoutdate: "21/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "09",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "25/03/2019",
            checkoutdate: "27/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "04",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "15/03/2019",
            checkoutdate: "17/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "04",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "25/03/2019",
            checkoutdate: "27/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "05",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        },
        {
            queryid: 4810,
            checkindate: "27/03/2019",
            checkoutdate: "29/03/2019",
            totalpassenger: 1,
            totalroom: 1,
            amount: 584999,
            hotelid: "471192",
            hotelname: "Khách sạn Boss Legend",
            hotel_address: "21 Hang Thung Street Hoan Kiem District Hanoi",
            hotel_thumb: "https://i.travelapi.com/hotels/9000000/8280000/8278400/8278380/f0ed4932_b.jpg",
            provinceid: 66,
            cityid: 0,
            areaid: 0,
            latitude: null,
            longtitude: null,
            status: "12",
            sourcebook: "Agribank",
            chanelbook: "Agribank",
            chanelpay: null,
            orderid: 0,
            ordertoken: null,
            paycode: "VNP/001A9A",
            pgdate: "",
            appmobile: "0389910504",
            createddate: "11/03/2019 09:37:01",
            ordernumber: null,
            supplier_order_number: null,
            paysource: null,
            paystatus: null,
            paydata: null,
            detail_description: null,
            issueTicketDate: "",
            extraInfo: null,
            is_expired: false,
            check_in_time: "14:00",
            check_out_time: "12:00",
            payment_expired_time: "11/03/2019 09:57:01",
            system_time: "18/03/2019 14:14:32",
            fullname: "Trieu Tiến Mạnh",
            email: "tienmanh@vnpay.vn",
            phone: "0984850112",
            roomdata: [{
                id: 4776,
                queryid: 4810,
                name: "Phòng phong cách cổ điển (Deluxe - free early check in 2hrs)",
                vat: 10,
                price: 584998,
                mealplan: "Không bao gồm bữa ăn",
                cancelpolicies: "Đây là giá không hoàn tiền. Nếu thay đổi hoặc hủy đặt phòng này, quý vị sẽ không nhận được bất kỳ khoản hoàn trả nào. Trường hợp Quý khách muốn hủy đặt phòng sau khi thực hiện thanh toán thành công (chỉ áp dụng đối với phòng có điều kiện được hoàn hủy), vui lòng liên hệ tổng đài 1900 55 55 20.",
                avaitoken: "bc4a1e380f5545878e5b0b25b92b2a65",
                hotelid: "471192",
                servicefee: 5,
                maxadult: 0,
                facilites: null,
                description: null,
                quantity: 0,
                extra_room_info: null
            }]
        }
    ],
    paging: {
        pageNo: 1,
        pageSize: 100,
        totalRow: 5,
        totalPage: 1
    }
}
module.exports = dataDemo;